apiVersion: v1
kind: Template
metadata: {}
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: tomcat9
  spec:
    lookupPolicy:
      local: false
    tags:
      - annotations: null
        from:
          kind: DockerImage
          name: 'tomcat:${TOMCAT_IMAGE_TAG}-jdk8-openjdk'
        generation: 1
        importPolicy: {}
        name: ${TOMCAT_IMAGE_TAG}-jdk8-openjdk
        referencePolicy:
          type: Local
  status:
    dockerImageRepository: ''
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: ${NAME}
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: ${NAME}
    name: ${NAME}-${BUILD_SUFFIX}
  spec:
    nodeSelector: null
    runPolicy: SerialLatestOnly
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:${TOMCAT_IMAGE_TAG}-${TAG_SUFFIX}
    postCommit: {}
    resources: {}
    source:
      contextDir: docker
      git:
        ref: ${SOURCE_GIT_REF}
        uri: ${SOURCE_GIT_URL}
      type: Git
    strategy:
      dockerStrategy:
        imageOptimizationPolicy: SkipLayers
        from:
          kind: ImageStreamTag
          name: tomcat9:${TOMCAT_IMAGE_TAG}-jdk8-openjdk
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
parameters:
- description: Name used for all created objects
  displayName: Name
  name: NAME
  value: ha-tomcat9
- description: A suffix appended to the build object.
  name: BUILD_SUFFIX
  value: build
- description: A suffix applied to the image's tag.
  name: TAG_SUFFIX
  value: latest
- description: The tag of the base Tomcat image.
  name: TOMCAT_IMAGE_TAG
  value: "9.0.27"
- name: SOURCE_GIT_URL
  value: https://github.com/BCDevOps/ha-tomcat9.git
- name: SOURCE_GIT_REF
  value: master